on: [pull_request, push]

name: Lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
          configDirectory: .
          srcDirectory: proto

