on: [pull_request, push]

name: Lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Buf lint
        run: buf lint --error-format github-actions

      - name: Buf format
        run: buf format --diff --exit-code